### ISSUE TITLE
Add MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [LeProfesseurStagiaire/FW_Godot_controller_use#1]
I noticed you submitted this project to the Godot Asset Library, but we require all assets to have clear licensing (you selected MIT in the submission form, but there's no copy of the license in the repository). Please add a [copy of the MIT license](https://choosealicense.com/licenses/mit/) to this repository, so that users know their rights :slightly_smiling_face:

**Comment by akien-mga** [comment]
Had to reject the asset submission for now as there is no license details: https://godotengine.org/asset-library/asset/edit/1096
Please resubmit it once a license has been added to this repository.

**Comment by Calinou** [comment]
This was added in https://github.com/LeProfesseurStagiaire/FW_Godot_controller_use/commit/bf71de96c05499926e4ca98759d92d2fb087618f, closing.
